### ISSUE TITLE
Working from localhost

### ISSUE THREAD

**Issue by borjadotai** [AnalogJ/goodreads.js#3]
Hi, amazing job here, probably the best wrapper I've found for the API. 
I'm having one issue though. 

`Failed to load https://www.goodreads.com/search.xml?q=crime%20and%20punishment&page=1&key=xxxxx&utf8=%E2%9C%93: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Any idea about how to fix this?

**Comment by AnalogJ** [comment]
thats a CORS header issue, its not possible to fix that as it requires Goodreads to change it on the server.
